ministryofjustice/money-to-prisoners-noms-ops

mtp_prisoner_location_admin/settings/jenkins.py, requirements/jenkins.txt
This configures django-jenkins so that jenkins can run unit tests and generate reports.
=> Add jenkins config files for running tests

bower.json, mtp_prisoner_location_admin/settings/base.py
=> read env variable to set GA tracking ID

.gitignore, .jshintrc, README.md, gulpfile.js, package.json, test/features/pages/dashboard.js, test/features/pages/signin.js, test/features/steps/auth.js, test/features/steps/shared.js, test/features/support/hooks.js, test/features/support/pagesMap.js, test/features/user_signin.feature, test/features/user_signout.feature, test/wdio.conf.js, test/wdio.headless.conf.js, test/wdio.wip.conf.js
Setup using cucumberjs to run gherkin style feature tests
[updates #103485730]
=> Add initial integration test setup

mtp_prisoner_location_admin/apps/prisoner_location_admin/forms.py, mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/__init__.py, mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/test_forms.py, mtp_prisoner_location_admin/templates/prisoner_location_admin/dashboard.html
depends on [api#46](https://github.com/ministryofjustice/money-to-prisoners-api/pull/46)
=> Prisoner name import

gulpfile.js
Seems to be a bug in gulp/browsersync
=> add delay to browsersyc reload

bower.json
in order to get the new feedback link copy
https://www.pivotaltracker.com/n/projects/1214032/stories/106947332
=> Use the latest version of common assets

mtp_prisoner_location_admin/settings/base.py, mtp_prisoner_location_admin/settings/prod.py
=> tightens security for cookies and provides another layer to enforce SSL

mtp_prisoner_location_admin/templates/prisoner_location_admin/location_file_upload.html, package.json
So that the whole file path is visible
[Updates #109017446]
=> Make file upload controls 100% wide

mtp_prisoner_location_admin/apps/feedback/urls.py, mtp_prisoner_location_admin/settings/base.py, mtp_prisoner_location_admin/templates/feedback/submit_feedback.html, mtp_prisoner_location_admin/urls.py, requirements/base.txt
This consists of a basic form which can be extended in
the future.
=> Add feedback page for submission of Zendesk tickets

mtp_prisoner_location_admin/apps/prisoner_location_admin/healthchecks.py, mtp_prisoner_location_admin/settings/base.py, mtp_prisoner_location_admin/urls.py, requirements/base.txt
depends on [django-moj-irat#1](https://github.com/ministryofjustice/django-moj-irat/pull/1)
=> Add a healthcheck.json view for IRaT support which tests MTP API & Zendesk connectivity

mtp_prisoner_location_admin/templates/prisoner_location_admin/location_file_upload.html
in order to display a message when necessary
[updates #110406604]
=> Use the new message box partial

package.json
Also include PhantomJS which will be needed shortly
=> Ensure MTP common node package always installs the latest version from master

mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/test_functional.py
depends on [mtp-common#58](https://github.com/ministryofjustice/money-to-prisoners-common/pull/58)
=> Allow functional testing from the command line to choose the web driver

mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/test_functional.py
depends on [mtp-api#104](https://github.com/ministryofjustice/money-to-prisoners-api/pull/104)
=> Tests can recreate data

mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/files/empty.csv, mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/test_functional.py
…they now contain header rows and tests hadn't been updated
=> Fix functional tests for invalid upload files

mtp_prisoner_location_admin/apps/prisoner_location_admin/forms.py, mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/test_functional.py, mtp_prisoner_location_admin/apps/prisoner_location_admin/views.py
… so that they get a visual check of how many they submitted (they're likely to know the rough number that should be added)
=> Report number of prisoner locations updated to ELK and to admin user

Dockerfile, Makefile, find_common.py, mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/test_code_style.py, mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/test_functional.py, mtp_prisoner_location_admin/settings/base.py, mtp_prisoner_location_admin/templates/base.html, mtp_prisoner_location_admin/templates/feedback/submit_feedback.html, mtp_prisoner_location_admin/templates/mtp_auth/login.html, mtp_prisoner_location_admin/templates/prisoner_location_admin/location_file_upload.html, mtp_prisoner_location_admin/urls.py, package.json, requirements/dev.txt, requirements/docker.txt
This new package combines the previous mtp-common, utils and user-admin
packages.
=> Update app to use new mtp-common package

mtp_prisoner_location_admin/templates/prisoner_location_admin/location_file_upload.html
Parto of https://www.pivotaltracker.com/story/show/117066137
=> Add warning for upload, and remove unneccessarily visible form label

mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/test_forms.py, mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/test_functional.py, mtp_prisoner_location_admin/assets-src/javascripts/main.js, mtp_prisoner_location_admin/templates/prisoner_location_admin/location_file_upload.html, requirements/dev.txt, requirements/docker.txt
Part of https://www.pivotaltracker.com/story/show/119005035
=> Use a new file upload component

mtp_prisoner_location_admin/apps/prisoner_location_admin/forms.py, mtp_prisoner_location_admin/apps/prisoner_location_admin/tests/test_views.py, mtp_prisoner_location_admin/settings/base.py, mtp_prisoner_location_admin/urls.py, requirements/base.txt, requirements/dev.txt, requirements/docker.txt
…because it's not used elsewhere and is highly specialised for MTP services' setup
=> Merge MoJ Auth package into MTP Common

find_common.py
as in some cases this script would be run before common is installed
=> Don't crash if common not found

mtp_noms_ops/templates/security/security_dashboard.html
https://www.pivotaltracker.com/story/show/119364823
=> Change to the right word

mtp_noms_ops/apps/security/forms.py, mtp_noms_ops/apps/security/tests/test_functional.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views.py, mtp_noms_ops/templates/security/dashboard.html
unlikely to be needed as anonymous payments will be blocked in the future
=> Remove unknown sender security view

mtp_noms_ops/apps/prisoner_location_admin/tests/test_functional.py, mtp_noms_ops/apps/prisoner_location_admin/urls.py, mtp_noms_ops/apps/security/forms.py, mtp_noms_ops/apps/security/tests/test_functional.py, mtp_noms_ops/apps/security/tests/test_utils.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views.py, mtp_noms_ops/settings/base.py, mtp_noms_ops/templates/base.html, mtp_noms_ops/urls.py, mtp_noms_ops/utils.py
…for users who can access both
=> Provide navigation between prisoner location upload and security views

mtp_noms_ops/assets-src/javascripts/main.js, mtp_noms_ops/settings/docker.py, mtp_noms_ops/settings/jenkins.py, requirements/dev.txt, requirements/docker.txt
as a side effect of [common#155](https://github.com/ministryofjustice/money-to-prisoners-common/pull/155/)
=> Harmonise JS file names and exported modules

mtp_noms_ops/assets-src/javascripts/modules/security-forms.js, mtp_noms_ops/assets-src/stylesheets/views/_security-forms.scss, mtp_noms_ops/templates/security/credits.html, mtp_noms_ops/templates/security/grouped-credits.html, mtp_noms_ops/templates/security/prisoner-grouped.html, mtp_noms_ops/templates/security/sender-grouped.html, requirements/dev.txt, requirements/docker.txt
~~…if accepted, the styles overridden from MTP common should be updated upstream~~
MTP common has been updated
=> Remove zebra stripes from tables and go for a more GDS style

mtp_noms_ops/apps/security/views.py, mtp_noms_ops/templates/security/dashboard.html, mtp_noms_ops/templates/security/search.html
partially completes #121502005 #121502017 #121502181
=> Update copy in security views

mtp_noms_ops/assets-src/stylesheets/views/_security-forms.scss
https://www.pivotaltracker.com/story/show/122124701
=> Don't use a smaller font size for sub-tables

mtp_noms_ops/apps/security/views.py, mtp_noms_ops/assets-src/javascripts/modules/security-forms.js, mtp_noms_ops/assets-src/stylesheets/views/_security-forms.scss, mtp_noms_ops/templates/security/grouped-credits-ajax.html, mtp_noms_ops/templates/security/prisoner-grouped-credits-ajax.html, mtp_noms_ops/templates/security/prisoner-grouped.html, mtp_noms_ops/templates/security/sender-grouped-credits-ajax.html, mtp_noms_ops/templates/security/sender-grouped.html
The Python part is poorly written -- please fix!
=> Simplify search details and reintroduce grouped credit pages

mtp_noms_ops/apps/security/forms.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_views.py
And remove querying by gender.
=> Allow for querying by prison type in security forms

mtp_noms_ops/apps/security/tests/test_functional.py, mtp_noms_ops/templates/security/credits.html
https://www.pivotaltracker.com/story/show/124485061
=> Add the name of the sender to the 'other' results

mtp_noms_ops/apps/security/tests/test_functional.py, mtp_noms_ops/assets-src/stylesheets/views/_security-forms.scss, mtp_noms_ops/templates/security/prisoner-grouped.html, mtp_noms_ops/templates/security/sender-grouped.html
https://www.pivotaltracker.com/story/show/122420821
https://www.pivotaltracker.com/story/show/122420671
=> Add more information in headers

mtp_noms_ops/assets-src/stylesheets/views/_security-form-fields.scss, mtp_noms_ops/templates/security/grouped-range-fields.html, mtp_noms_ops/templates/security/received-range-field.html
https://www.pivotaltracker.com/story/show/124485061
=> Make form labels bold, except 'sublabels'

mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/templates/security/prisoner-grouped.html, mtp_noms_ops/templates/security/sender-grouped.html
Part of https://www.pivotaltracker.com/story/show/121503857
=> Sort group results by sender or prisoner

mtp_noms_ops/apps/security/forms.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/templates/security/credits-form.html, mtp_noms_ops/templates/security/grouped-range-fields.html, mtp_noms_ops/templates/security/numeric-range-field.html, mtp_noms_ops/templates/security/prisoner-grouped-form.html, mtp_noms_ops/templates/security/select-field.html, mtp_noms_ops/templates/security/sender-grouped-form.html
By sender:
Min/max number of credits sent
Sender roll number
By prisoner:
Min/max number of credits sent
Prison region, type and category
Other:
Prison region, type and category
=> Add additional fields to security search forms

mtp_noms_ops/apps/security/forms.py, mtp_noms_ops/templates/security/select-field.html
https://www.pivotaltracker.com/story/show/121502005/comments/143665267
https://www.pivotaltracker.com/story/show/124485061
=> Add 'minimum' to label and a sort button for no-js browsers

mtp_noms_ops/assets-src/stylesheets/app.scss, mtp_noms_ops/assets-src/stylesheets/views/_security-forms.scss, mtp_noms_ops/templates/security/credits.html, mtp_noms_ops/templates/security/grouped-credits.html, mtp_noms_ops/templates/security/grouped.html, mtp_noms_ops/templates/security/search.html
Reduce some margins in order not to waste screen space
https://www.pivotaltracker.com/story/show/126227051
=> Add the help text on all search results screen

mtp_noms_ops/assets-src/stylesheets/views/_security-forms.scss, mtp_noms_ops/templates/feedback/submit_feedback.html, mtp_noms_ops/templates/security/credits.html, mtp_noms_ops/templates/security/grouped.html, mtp_noms_ops/templates/security/pagination.html, mtp_noms_ops/templates/security/search.html, requirements/dev.txt, requirements/docker.txt
- move the no-printing information to the component level
and not the template level
- use latest common assets where printing is also fixed
=> Fix printing:

mtp_noms_ops/templates/security/credits.html, mtp_noms_ops/templates/security/grouped-credits-ajax.html, mtp_noms_ops/templates/security/grouped-credits.html
https://www.pivotaltracker.com/story/show/121510537
=> Replace wording of 'intended recipient'

mtp_noms_ops/templates/security/grouped-credits-ajax.html, mtp_noms_ops/templates/security/grouped-credits.html, mtp_noms_ops/templates/security/sender-grouped.html
- Credit status
- Prisoner's current prison (stub)
https://www.pivotaltracker.com/story/show/121503857
=> Add more info on credits

mtp_noms_ops/templates/security/credits.html, mtp_noms_ops/templates/security/grouped-credits-ajax.html, mtp_noms_ops/templates/security/grouped-credits.html, mtp_noms_ops/templates/security/prisoner-grouped.html, requirements/dev.txt, requirements/docker.txt
Add status to 'seach by other'
Add current prison to 'search by prisoner'
Change column heading from 'processed by' to 'credited by'
=> Add additional details to search results screen

mtp_noms_ops/apps/security/views.py
…fixes a bug where inner credits list in grouped credits returned the home page for unknown senders
[Fixes #127565017]
depends on [api#234](https://github.com/ministryofjustice/money-to-prisoners-api/pull/234)
=> Allow filtering credits with blank sender details

requirements/dev.txt, requirements/docker.txt
Includes tabable collapse buttons.
=> Increse required version of mtp common library

mtp_noms_ops/urls.py, requirements/dev.txt, requirements/docker.txt
but currently, no link is provided in the navigation (TBD in navigation discussion)
=> Add user account management

mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/apps/security/views.py, mtp_noms_ops/templates/security/credits.html, mtp_noms_ops/templates/security/grouped-credits-ajax.html, mtp_noms_ops/templates/security/grouped-credits.html
depends on [api#241](https://github.com/ministryofjustice/money-to-prisoners-api/pull/241)
=> Security view tweaks

mtp_noms_ops/apps/security/forms.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/templates/security/received-range-field.html
The API now uses __gte, __lt rather than _0, _1.
=> Update received_at filter to use new API format

mtp_noms_ops/apps/feedback/urls.py, mtp_noms_ops/apps/prisoner_location_admin/tests/test_functional.py, mtp_noms_ops/apps/security/tests/test_functional.py, mtp_noms_ops/apps/security/views.py, mtp_noms_ops/assets-src/javascripts/main.js, mtp_noms_ops/assets-src/stylesheets/app.scss, mtp_noms_ops/settings/base.py, mtp_noms_ops/templates/base.html, mtp_noms_ops/templates/feedback/submit_feedback.html, mtp_noms_ops/templates/feedback/success.html, mtp_noms_ops/templates/security/credits-help.html, mtp_noms_ops/templates/security/credits.html, mtp_noms_ops/templates/security/dashboard.html, mtp_noms_ops/templates/security/grouped.html, mtp_noms_ops/templates/security/prisoner-grouped-help.html, mtp_noms_ops/templates/security/search.html, mtp_noms_ops/templates/security/select-field.html, mtp_noms_ops/templates/security/sender-grouped-help.html, mtp_noms_ops/urls.py, mtp_noms_ops/utils.py, requirements/dev.txt, requirements/docker.txt
- add breadcrumbs to non-top-level pages
- improve styling of navigation links on mobile and tablet and re-order
=> Wayfinding

Dockerfile, conf/uwsgi/noms_ops.ini, mtp_noms_ops/apps/prisoner_location_admin/forms.py, mtp_noms_ops/apps/prisoner_location_admin/tasks.py, mtp_noms_ops/apps/prisoner_location_admin/tests/test_forms.py, mtp_noms_ops/apps/prisoner_location_admin/tests/test_views.py, mtp_noms_ops/apps/prisoner_location_admin/views.py, mtp_noms_ops/settings/base.py, mtp_noms_ops/templates/prisoner_location_admin/email/failure-notification.html, mtp_noms_ops/templates/prisoner_location_admin/email/failure-notification.txt, requirements/base.txt, requirements/docker.txt
If the application is running in a uwsgi context, then when a user
uploads a prisoner location file it is saved a job is spooled to
upload it to the backend API in chunks. If this occurs, the user
who uploaded the file will be sent an email notification if there
are any problems encountered when uploading the file.
=> Upload prisoner locations asynchronously using uwsgi spooler

mtp_noms_ops/settings/base.py, mtp_noms_ops/templates/prisoner_location_admin/location_file_upload.html, mtp_noms_ops/templates/security/credits.html, mtp_noms_ops/templates/security/dashboard.html, mtp_noms_ops/templates/security/grouped-credits.html, mtp_noms_ops/templates/security/grouped.html, mtp_noms_ops/templates/security/review.html, mtp_noms_ops/templates/security/search.html, requirements/dev.txt, requirements/docker.txt
=> Add language switching

mtp_noms_ops/apps/prisoner_location_admin/forms.py, mtp_noms_ops/apps/prisoner_location_admin/tests/__init__.py, mtp_noms_ops/apps/prisoner_location_admin/tests/test_forms.py
Excel ensures that all rows of the file have the same number of
rows.
=> Allow for excel formatted version of prisoner location CSV

mtp_noms_ops/apps/security/forms.py
and nginx config from template deploy has no mechanism to increase proxy buffer size to copy with it
=> Do not store prison list in session as cookie is >3kb

mtp_noms_ops/assets-src/javascripts/modules/security-forms.js, mtp_noms_ops/assets-src/stylesheets/views/_security-form-fields.scss, mtp_noms_ops/templates/security/credits-form.html, mtp_noms_ops/templates/security/senders-form.html
- add toggle for relevant payment type fields
- remove some uneccesary styles
=> Add payments type filter

mtp_noms_ops/apps/security/forms.py, mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_functional.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/templates/security/forms/credits.html, mtp_noms_ops/templates/security/forms/prisoners.html, mtp_noms_ops/templates/security/forms/senders.html
and preserve current ordering on filter changes
=> Fix bug which cleared amount filters when pagination or ordering changed

mtp_noms_ops/apps/security/utils.py, mtp_noms_ops/settings/base.py, mtp_noms_ops/templates/base.html, mtp_noms_ops/templates/dashboard.html, requirements/dev.txt, requirements/docker.txt
This only applies when the user has a single associated
prison.
=> Filter results by the user's associated prison by default

mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/views.py, mtp_noms_ops/templates/security/prisoners-detail.html, mtp_noms_ops/templates/security/senders-detail.html, mtp_noms_ops/translations/cy/LC_MESSAGES/django.po, mtp_noms_ops/translations/en_GB/LC_MESSAGES/django.po
depends on [api#332](https://github.com/ministryofjustice/money-to-prisoners-api/pull/332)
=> Prisoner recipient names

mtp_noms_ops/assets-src/javascripts/modules/tabs.js, mtp_noms_ops/templates/security/forms/credits.html, mtp_noms_ops/templates/security/forms/prisoners.html, mtp_noms_ops/templates/security/forms/senders.html
or if there’s an error in another tab
=> Keep security form tabs open until explicitly changed or closed

mtp_noms_ops/apps/security/forms.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/templates/security/senders.html
depends on [api#339](https://github.com/ministryofjustice/money-to-prisoners-api/pull/339)
=> Allow ordering and filtering senders by prison count

.dockerignore, Dockerfile, mtp_noms_ops/apps/prisoner_location_admin/forms.py, mtp_noms_ops/apps/prisoner_location_admin/tasks.py, mtp_noms_ops/apps/prisoner_location_admin/views.py, mtp_noms_ops/tasks.py, noms_ops.ini, requirements/dev.txt, requirements/docker.txt
and make uwsgi.ini usable outside docker
depends on [common#255](https://github.com/ministryofjustice/money-to-prisoners-common/pull/255)
=> Use MTP-common’s spoolable mechanism for prisoner location uploader

mtp_noms_ops/assets-src/javascripts/main.js, mtp_noms_ops/assets-src/stylesheets/views/_security-forms.scss, mtp_noms_ops/templates/prisoner_location_admin/location_file_upload.html, mtp_noms_ops/templates/security/forms/numeric-range-field.html, mtp_noms_ops/templates/security/forms/received-range-field.html, mtp_noms_ops/templates/security/forms/select-field.html, mtp_noms_ops/templates/security/review.html, requirements/base.txt, requirements/dev.txt, requirements/docker.txt
depends on [common#258](https://github.com/ministryofjustice/money-to-prisoners-common/pull/258)
=> Use latest GOV.UK styles and new appearance of page list links

Dockerfile, mtp_noms_ops/assets-src/stylesheets/views/_prisoners-detail.scss, mtp_noms_ops/assets-src/stylesheets/views/_senders-detail.scss, noms_ops.ini, requirements/dev.txt, requirements/docker.txt
This updates
• the base container to Ubuntu Xenial
• node.js to version 8
• python to version 3.5
=> Docker upgrades

mtp_noms_ops/apps/security/forms.py
Due to the fact that the forms use inclusive end dates but the
api uses exclusive end dates, the end date needs to be modified
prior to any communication with the api.
=> Fix date filtering on exported data

mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/utils.py, mtp_noms_ops/apps/security/views.py, mtp_noms_ops/settings/base.py
…because it's on for all prisons now
=> Remove switch for NOMIS integration availability

mtp_noms_ops/templates/dashboard.html, mtp_noms_ops/urls.py
=> Show message on dashboard depending on whether user is in disbursement pilot prison

mtp_noms_ops/apps/security/forms/preferences.py
Abssence of prison is in empty list or something.
=> Fix error when submitting empty prison confirmation form

mtp_noms_ops/apps/security/views/notifications.py, mtp_noms_ops/templates/security/includes/notification-table.html
Have switched to creating events for monitored payments for
consistency with other notifications.
=> Retrieve monitored payments from the event endpoint

requirements/dev.txt, requirements/docker.txt
… as it's true 99% of the time
=> Add note to login page about username==Quantum ID

README.md, mtp_noms_ops/apps/prisoner_location_admin/forms.py, mtp_noms_ops/apps/security/forms/object_base.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/views/eligibility.py, mtp_noms_ops/apps/settings/forms.py, mtp_noms_ops/apps/settings/views.py
This:
- adds/corrects a few lines in the README
- removes unused lines
- makes sure mutable data structures are not used for arg defaults
- changes another couple of things
The intention is to eventually add `flake8-bugbear` and `flake8-quotes` to mtp_common.
=> Housekeeping

mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/assets-src/stylesheets/views/_security-results.scss, mtp_noms_ops/templates/security/credits_list.html, requirements/dev.txt, requirements/docker.txt
This adds changes the results list for credits
**Before**
**After**
=> Redesign results list for credits

mtp_noms_ops/apps/security/forms/object_list.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views/__init__.py, mtp_noms_ops/apps/security/views/object_list.py, mtp_noms_ops/templates/base.html, mtp_noms_ops/templates/security/credits.html, mtp_noms_ops/templates/security/disbursements_list.html
This implements simple search for disbursements.
=> Disbursements simple search box

mtp_noms_ops/templates/security/credits_list.html, mtp_noms_ops/templates/security/disbursements_list.html
=> Redesign results list for disbursements

mtp_noms_ops/apps/security/export.py, mtp_noms_ops/apps/security/forms/object_list.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views/__init__.py, mtp_noms_ops/apps/security/views/object_list.py, mtp_noms_ops/assets-src/stylesheets/views/_security-results.scss, mtp_noms_ops/templates/base.html, mtp_noms_ops/templates/security/prisoners_list.html, requirements/dev.txt, requirements/docker.txt
This implements simple search for prisoners.
It looks like this:
=> Prisoners simple search box

mtp_noms_ops/apps/security/forms/object_list.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_utils.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/utils.py, mtp_noms_ops/apps/security/views/object_base.py, mtp_noms_ops/apps/security/views/object_list.py, mtp_noms_ops/assets-src/stylesheets/views/_security-form-fields.scss, mtp_noms_ops/templates/security/forms/top-area-object-list.html, mtp_noms_ops/templates/security/senders_advanced_search.html, mtp_noms_ops/templates/security/senders_list.html
This implements advanced search for senders.
Note:
1. the prison field has not been added yet as it needs some design thinking
2. the prison switcher has not been removed yet because of point 1
=> Advanced search for senders (payment sources)

mtp_noms_ops/apps/security/forms/object_base.py, mtp_noms_ops/apps/security/forms/object_list.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views/object_list.py, mtp_noms_ops/assets-src/stylesheets/views/_security-form-fields.scss, mtp_noms_ops/templates/security/base_advanced_search.html, mtp_noms_ops/templates/security/prisoners_advanced_search.html, mtp_noms_ops/templates/security/prisoners_list.html, mtp_noms_ops/templates/security/senders_advanced_search.html, mtp_noms_ops/templates/security/senders_list.html
This implements advanced search for prisoners.
Note:
1. the prison field has not been added as it needs some design thinking
2. the prison switcher has not been removed yet because of point 1
3. the 'show prisoners no longer in custody' field has not been added as it only makes sense if you can override 'your prisons' setting
=> Advanced search for prisoners

mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/assets-src/stylesheets/app-ie8.scss, mtp_noms_ops/assets-src/stylesheets/views/_login.scss, mtp_noms_ops/templates/base.html, mtp_noms_ops/templates/mtp_auth/login.html, requirements/dev.txt, requirements/docker.txt
=> Add a banner for IE8-only display to indicate that users should switch browser

mtp_noms_ops/apps/security/forms/object_list.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views/object_list.py, mtp_noms_ops/assets-src/stylesheets/views/_security-form-fields.scss, mtp_noms_ops/templates/base.html, mtp_noms_ops/templates/security/disbursements_advanced_search.html, mtp_noms_ops/templates/security/disbursements_list.html
This doesn't include:
- Show prisoners no longer in custody
- Prisons
- Cheque
as they need more design thinking.
=> Disbursements advanced search

mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/views/object_base.py
Before: an API call was made when the advanced search form was rendered
After: that API call is not made as the user has not hit search yet
=> Advanced search optimisation

mtp_noms_ops/templates/dashboard.html
This adds prison switcher to the dashboard if the logged in user can see search V2.
=> Add prison switcher to dashboard

mtp_noms_ops/templates/security/credits_advanced_search.html, mtp_noms_ops/templates/security/senders_advanced_search.html
=> Change copy to say sender in advanced search

mtp_noms_ops/apps/security/forms/object_list.py, mtp_noms_ops/apps/security/tests/test_forms.py
If the user selects a payment method that is not `debit card`, some of the sender fields (`email`, `postcode`, `ip_address`) do not make sense.
Before: the form would validate and the search would return 0 records.
After: the form errors so that the user is aware that those fields cannot be used when payment method is not 'debit card'.
=> Show errors when conflicting search filters are used

noms_ops.ini, requirements/base.txt
… in the hope of making it work better with keep-alive/connection pooling issues that originate in urllib3.
also:
- simplify logging (CP kibana does not expand json logs into fields)
- add uwsgi stats server (only available inside container)
- hopefully improve k8s/docker compatibility
=> Update uWSGI options

mtp_noms_ops/apps/security/forms/object_list.py, mtp_noms_ops/templates/security/credits_list.html, mtp_noms_ops/templates/security/disbursements_list.html, mtp_noms_ops/templates/security/prisoners_list.html, mtp_noms_ops/templates/security/senders_list.html
This:
**a.** Changes the text in button from "Search again" to "Start new search"
**b.** Changes the search description on search results pages:
From:
- Results that contain the prisoner number or the name "..."
- Results from all prisons that contain the prisoner number or the name "..."
To:
- Results containing "..." in your selected prison(s)
- Results containing "..." in all prisons
=> Search v2 rewording

mtp_noms_ops/apps/security/export.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/utils.py, mtp_noms_ops/templates/security/credit.html
which is the time a user was on the website (i.e. at ip address)
=> Add payment started time to credit history

mtp_noms_ops/apps/security/forms/check.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_utils.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/utils.py, mtp_noms_ops/apps/security/views/__init__.py, mtp_noms_ops/apps/security/views/check.py, mtp_noms_ops/assets-src/stylesheets/app.scss, mtp_noms_ops/assets-src/stylesheets/views/_checks.scss, mtp_noms_ops/templates/base.html, mtp_noms_ops/templates/security/checks_list.html, mtp_noms_ops/utils.py
This implements the check list in pending state. 
The accept/reject buttons don't do anything at the moment.
Layout and wording will change slightly in the future so I didn't rely too much on the current prototype (e.g. I've used _payments pending_ everywhere instead of _delayed capture_ for consistency).
_x Payments pending for over 3 days_ is also missing
=> Security checks list

mtp_noms_ops/apps/security/forms/check.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/assets-src/stylesheets/views/_checks.scss, mtp_noms_ops/assets-src/stylesheets/views/_security-results.scss, mtp_noms_ops/templates/security/accept_check.html, mtp_noms_ops/templates/security/checks_list.html, mtp_noms_ops/templates/security/reject_check.html
depends on [api#563](https://github.com/ministryofjustice/money-to-prisoners-api/pull/563)
=> Show how many checks need attention

mtp_noms_ops/apps/security/forms/check.py, mtp_noms_ops/apps/security/tests/test_views.py
…so that the list does not vary throughout the day
=> Display all checks that would need attention today as needing attention now

mtp_noms_ops/apps/security/searches.py
…but don't update the new results count
=> Show saved searches on dashboard even when there are too many to update

mtp_noms_ops/apps/feedback/urls.py
not directly related to, but helps with ticket MTP-1366
=> Make it clearer who Zendesk tickets are meant for

mtp_noms_ops/apps/security/forms/check.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views/__init__.py, mtp_noms_ops/apps/security/views/check.py, mtp_noms_ops/assets-src/stylesheets/app.scss, mtp_noms_ops/assets-src/stylesheets/views/_prisoners-detail.scss, mtp_noms_ops/assets-src/stylesheets/views/_tags.scss, mtp_noms_ops/templates/base.html, mtp_noms_ops/templates/security/checks_list.html, mtp_noms_ops/templates/security/credits_history_list.html
Design for the Decision history view:
=> Decision history view

mtp_noms_ops/apps/security/forms/check.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/assets-src/stylesheets/views/_checks.scss, mtp_noms_ops/assets-src/stylesheets/views/_tags.scss, mtp_noms_ops/templates/security/accept_or_reject_check.html, mtp_noms_ops/templates/security/checks_list.html, mtp_noms_ops/templates/security/credits_history_list.html
cosmetic changes to make the 3 security check pages look more alike: tables with checks have the same info in the same places and are styled in the same way
=> Normalise security check pages' appearance

mtp_noms_ops/apps/security/models.py, mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/apps/security/views/check.py, mtp_noms_ops/templates/base.html, mtp_noms_ops/templates/dashboard.html, mtp_noms_ops/templates/security/accept_or_reject_check.html, mtp_noms_ops/templates/security/credits_history_list.html
[MTP-1312](https://dsdmoj.atlassian.net/browse/MTP-1312)
=> Change pending label in Checks to To action

mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views/check.py, mtp_noms_ops/assets-src/stylesheets/views/_checks.scss, mtp_noms_ops/templates/security/checks_list.html
I'm leaving this in draft for now as I wanted both of your opinions on the approach here. I'm not convinced of it myself and I wanted to run it by you to see if you had any better ideas
=> MTP-1454 add to my list button visualisation on list view

mtp_noms_ops/apps/security/forms/check.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/views/check.py
https://dsdmoj.atlassian.net/browse/MTP-1485
https://dsdmoj.atlassian.net/browse/MTP-1486
=> MTP-1485 MTP-1486 add to list bugs

mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_utils.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/templates/security/accept_or_reject_check.html, mtp_noms_ops/templates/security/checks_list.html, mtp_noms_ops/templates/security/credits_history_list.html
…this change depends on [a data migration in the api](https://github.com/ministryofjustice/money-to-prisoners-api/pull/603)
[MTP-1488](https://dsdmoj.atlassian.net/browse/MTP-1488)
=> Add label to highlight the description of rules a security check matched

mtp_noms_ops/apps/security/forms/eligibility.py, mtp_noms_ops/templates/hmpps-employee.html
Security staff in contracted prisons are permitted access so we should make that clear in the eligibility check
[MTP-1503](https://dsdmoj.atlassian.net/browse/MTP-1503) ~[MTP-1536](https://dsdmoj.atlassian.net/browse/MTP-1536)~
=> Update eligibility note to include contracted estate

mtp_noms_ops/apps/feedback/urls.py, mtp_noms_ops/apps/prisoner_location_admin/tasks.py, mtp_noms_ops/apps/prisoner_location_admin/tests/__init__.py, mtp_noms_ops/apps/prisoner_location_admin/tests/test_forms.py, mtp_noms_ops/apps/prisoner_location_admin/tests/test_functional.py, mtp_noms_ops/apps/prisoner_location_admin/tests/test_views.py, mtp_noms_ops/apps/prisoner_location_admin/views.py, mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/apps/security/tests/test_functional.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/views/check.py, mtp_noms_ops/apps/security/views/eligibility.py, mtp_noms_ops/apps/security/views/object_base.py, mtp_noms_ops/apps/security/views/object_detail.py, mtp_noms_ops/apps/security/views/object_list.py, mtp_noms_ops/apps/security/views/review.py, mtp_noms_ops/apps/settings/tests/test_views.py, mtp_noms_ops/apps/settings/views.py, mtp_noms_ops/assets-src/javascripts/modules/security-forms.js, mtp_noms_ops/settings/base.py, mtp_noms_ops/urls.py, mtp_noms_ops/utils.py, requirements/base.txt, requirements/dev.txt, requirements/docker.txt
…and update uwsgi and django-anymail dependencies that include bug fixes [MTP-1519](https://dsdmoj.atlassian.net/browse/MTP-1519) (depends on [common-380](https://github.com/ministryofjustice/money-to-prisoners-common/pull/380))
also fixes display of focused links in Chrome/Edge [MTP-1514](https://dsdmoj.atlassian.net/browse/MTP-1514)
=> Use a single consistent version requirement for Django in all apps

mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views/__init__.py, mtp_noms_ops/apps/security/views/views.py, mtp_noms_ops/templates/dashboard.html, mtp_noms_ops/templates/security/credits_list.html, mtp_noms_ops/templates/security/disbursements_list.html, mtp_noms_ops/templates/security/policy-change-info.html
This is similar to the cashbook changes, but with different copy specifically for Intelligence tool.
=> Update pre Nov 2nd warning to include a change detail page to reduce banner copy

mtp_noms_ops/apps/security/constants.py, mtp_noms_ops/apps/security/forms/check.py, mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/views/check.py, mtp_noms_ops/assets-src/javascripts/main.js, mtp_noms_ops/assets-src/javascripts/modules/toggle-text-field-on-change.js, mtp_noms_ops/assets-src/stylesheets/views/_checks.scss, mtp_noms_ops/templates/security/accept_or_reject_check.html, mtp_noms_ops/templates/security/credits_history_list.html, requirements/dev.txt
=> MTP-1654 delayed capture categorisation

mtp_noms_ops/apps/security/models.py, mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/templates/security/accept_or_reject_check.html, mtp_noms_ops/templates/security/credits_history_list.html
Jira: https://dsdmoj.atlassian.net/browse/MTP-1736
=> MTP-1736 review credit review status

mtp_noms_ops/apps/security/constants.py, mtp_noms_ops/apps/security/forms/check.py, mtp_noms_ops/apps/security/forms/object_base.py, mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/utils.py, mtp_noms_ops/apps/security/views/__init__.py, mtp_noms_ops/apps/security/views/check.py, mtp_noms_ops/templates/security/auto_accept_rule_list.html, mtp_noms_ops/templates/security/checks_list.html, mtp_noms_ops/templates/security/credits_history_list.html
Jira: https://dsdmoj.atlassian.net/browse/MTP-1734
Related PRs
API: https://github.com/ministryofjustice/money-to-prisoners-api/pull/634
TODO
=> MTP-1734 auto accept lists

mtp_noms_ops/apps/security/forms/check.py, mtp_noms_ops/apps/security/tests/test_forms.py, mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/utils.py, mtp_noms_ops/apps/security/views/__init__.py, mtp_noms_ops/apps/security/views/check.py, mtp_noms_ops/apps/security/views/object_base.py, mtp_noms_ops/templates/security/auto_accept_rule.html, mtp_noms_ops/templates/security/auto_accept_rule_list.html, requirements/dev.txt
Jira: https://dsdmoj.atlassian.net/browse/MTP-1735
Linked PR: https://github.com/ministryofjustice/money-to-prisoners-api/pull/638
TODO:
=> MTP-1735 auto accept review page

mtp_noms_ops/apps/security/tests/test_views.py, mtp_noms_ops/assets-src/stylesheets/views/_checks.scss, mtp_noms_ops/templates/security/accept_or_reject_check.html, mtp_noms_ops/templates/security/credits_history_list.html
Jira: https://dsdmoj.atlassian.net/browse/MTP-1736
=> MTP-1736 Added auto-accepts to decision history view

mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views/__init__.py, mtp_noms_ops/apps/security/views/views.py, mtp_noms_ops/settings/base.py, mtp_noms_ops/templates/govuk-frontend/components/footer.html, mtp_noms_ops/templates/mtp_common/components/header-app-links.html, mtp_noms_ops/templates/security/faq.html
⚠️ **IMPORTANT**: Before deploying, remember to re-apply the kubernetes templates so that [the FIU_EMAIL secret (see PR)](https://github.com/ministryofjustice/money-to-prisoners-deploy/pull/312) is set by running `./manage.py app apply {test,prod}`
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1836
=> Security FAQ (signed in)

.gitignore, mtp_noms_ops/assets-src/components/checkbox-with-conditional-subfields/index.js, mtp_noms_ops/assets-src/components/choose-prisons/index.js, mtp_noms_ops/assets-src/components/security/index.js, mtp_noms_ops/templates/security/forms/top-area-object-list.html, mtp_noms_ops/templates/security/review.html, requirements/base.txt, requirements/dev.txt
Largely updates upstream dependencies, but also includes new button group visual component (buttons placed side-by-side) from GOV.UK design system and better print layouts.
=> Bundle of fixes and updates related to GOV.UK Design System update

mtp_noms_ops/apps/mtp_auth/forms.py, mtp_noms_ops/apps/mtp_auth/views.py, mtp_noms_ops/apps/security/views/dashboard.py, mtp_noms_ops/templates/dashboard.html, mtp_noms_ops/templates/mtp_common/user_admin/accept-request.html, mtp_noms_ops/templates/security/includes/account-requests-banner.html, mtp_noms_ops/urls.py
- FIU see a banner with the number of 'security' account requests
(when there are any)
- FIU can manage users and accept/reject these account requests
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1818
=> MTP-1818: Ability to accept/reject Account Requests

mtp_noms_ops/apps/security/forms/check.py
…if a containing checkbox is selected (i.e. present in `form.cleaned_data`), contained subfields become required so that it's not only JS that can ensure they work correctly
TODO: perhaps these conditional fields need to remove their subfields' values from `self.cleaned_data` if not selected in case javascript is not enabled. The situation being: something is entered into a subfield but the containing checkbox is not checked. With javascript, the subfields become disabled so are not sent to the backend so are effectively treated as empty. Without javascript, the subfields remain enabled so backend will treat it as though the checkbox was selected.
=> Add server-side validation to conditional fields

mtp_noms_ops/templates/govuk-frontend/components/footer.html, mtp_noms_ops/templates/mtp_common/components/header-app-links.html, mtp_noms_ops/utils.py
This is consistent with what's in `cashbook`.
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1872
=> Change 'help' links to 'Get help'

mtp_noms_ops/apps/prisoner_location_admin/tasks.py, mtp_noms_ops/apps/security/forms/check.py, mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/apps/security/utils.py, mtp_noms_ops/apps/security/views/nomis.py, mtp_noms_ops/apps/settings/forms.py, requirements/base.txt, requirements/dev.txt
Jira: https://dsdmoj.atlassian.net/browse/MTP-1863
* Moved dynamic fields out of logger.error/warning and exceptions to allow for sentry to deduplicate
Depends on [common#419](https://github.com/ministryofjustice/money-to-prisoners-common/pull/419)
=> MTP-1863 Remove remaining identifiers from exceptions and attach to sentry metadata 

mtp_noms_ops/urls.py
C.f. https://ministryofjustice.github.io/security-guidance/implement-security-txt/
=> Add /.well-known/security.txt redirect

mtp_noms_ops/settings/base.py, mtp_noms_ops/settings/docker.py, requirements/base.txt, requirements/dev.txt
and make settings configuration a bit simpler
=> Fix Sentry SDK initialisation

Dockerfile-dev, mtp_noms_ops/settings/base.py
…to make all MTP apps easier to run locally in concert
Depends on [mtp-common#429](https://github.com/ministryofjustice/money-to-prisoners-common/pull/429)
=> Update docker-compose spec

mtp_noms_ops/settings/base.py, requirements/base.txt, requirements/dev.txt
… which includes utility to upload to and download from S3 bucket
=> Use latest mtp-common

mtp_noms_ops/templates/prisoner_location_admin/location_file_upload.html
The instructions were a bit sparse. Because I do this so rarely, I actually have to look at my own notes each time I need to find the report.
=> Give full name of NOMIS report providing prisoner locations

mtp_noms_ops/assets-src/components/choose-prisons/index.js, requirements/base.txt, requirements/dev.txt
…fixing templates to work with latest GOV.UK frontend
=> Update mtp-common and dependencies

mtp_noms_ops/assets-src/components/choose-prisons/index.js, mtp_noms_ops/assets-src/components/form-analytics/index.js, mtp_noms_ops/settings/base.py, requirements/base.txt, requirements/dev.txt
=> MTP-1937: GA4 support

mtp_noms_ops/apps/prisoner_location_admin/forms.py, mtp_noms_ops/apps/prisoner_location_admin/management/commands/load_locations_from_offender_search.py, mtp_noms_ops/apps/prisoner_location_admin/models.py, mtp_noms_ops/apps/prisoner_location_admin/tests/__init__.py, mtp_noms_ops/apps/prisoner_location_admin/tests/test_forms.py, mtp_noms_ops/apps/prisoner_location_admin/tests/test_management_commands.py, mtp_noms_ops/apps/prisoner_location_admin/tests/test_views.py, mtp_noms_ops/apps/security/models.py, mtp_noms_ops/settings/base.py
…as an automated replacement for manually uploading CSV report saved from NOMIS. For now, the management command is _not_ scheduled to run periodically.
=> MTP-1957: Load prisoner locations from offender search

mtp_noms_ops/templates/mtp_auth/login.html, requirements/base.txt, requirements/dev.txt
… and use new password input component on login page
=> MTP-1980: Upgrade to govuk-frontend 5.3

mtp_noms_ops/apps/security/forms/object_list.py, mtp_noms_ops/apps/security/templatetags/security.py, mtp_noms_ops/apps/security/tests/test_forms/test_search_forms.py, mtp_noms_ops/apps/security/tests/test_views/test_search.py, mtp_noms_ops/apps/security/urls.py, mtp_noms_ops/apps/security/views/__init__.py, mtp_noms_ops/apps/security/views/object_list.py, mtp_noms_ops/assets-src/components/security/_checks-sub-navigation.scss, mtp_noms_ops/assets-src/components/security/_results-profile.scss, mtp_noms_ops/templates/mtp_common/components/header-app-links.html, mtp_noms_ops/templates/security/credits_list.html, mtp_noms_ops/templates/security/disbursements_list.html, mtp_noms_ops/templates/security/includes/checks-sub-navigation.html, mtp_noms_ops/templates/security/includes/prisoner-sub-navigation.html, mtp_noms_ops/templates/security/includes/prisoners-sub-navigation.html, mtp_noms_ops/templates/security/prisoner-disbursements.html, mtp_noms_ops/templates/security/prisoner.html, mtp_noms_ops/templates/security/prisoners_list-disbursements.html, mtp_noms_ops/templates/security/prisoners_list.html, mtp_noms_ops/templates/security/sender.html, mtp_noms_ops/templates/security/senders_list.html, requirements/base.txt, requirements/dev.txt
… so that credits and disbursements are listed on separate page loads
=> MTP-1953: Split prisoner search lists
