ministryofjustice/money-to-prisoners-noms-ops

- .bowerrc
- .editorconfig
- .gitignore
- .jshintrc
- Dockerfile
- bower.json
- gulpfile.js
- mtp_prisoner_location_admin/assets-src/stylesheets/app-print.scss
- mtp_prisoner_location_admin/assets-src/stylesheets/app.scss
- mtp_prisoner_location_admin/settings/base.py
- mtp_prisoner_location_admin/templates/base.html
- mtp_prisoner_location_admin/templates/mtp_auth/login.html
- package.json
- requirements/base.txt
Assets are now being shared across all 3 frontend app and
are coming from money-to-prisoners-common. This adds the setup needed
to import assets/templates from that package.
This change is part of the following story:
As a frontend developer,
I want assets/templates used across all frontend apps to be consistent and shared,
So that I don't have to make changes in multiple locations
> Add shared assets setup

- mtp_prisoner_location_admin/assets-src/javascripts/main.js
- because there's no user need for it
- and it uses keys() that IE8 doesn't implement
> Remove JS module information printed on the console

- mtp_prisoner_location_admin/settings/base.py
- mtp_prisoner_location_admin/templates/base.html
- package.json
depends on [django-utils#7](https://github.com/ministryofjustice/django-utils/pull/7)
NB: tests will likely fail until that PR is merged
> Add Sentry exception handling for JavaScript

- package.json
By virtue of using the latest common assets, we are now using the latest mojular
where all use of console.log (which is a problem with legacy browsers) is removed.
> Use the latest common assets resulting in no console.log use

- mtp_prisoner_location_admin/apps/feedback/urls.py
- package.json
This page will confirm that the ticket was submitted and
provide a link back to where the user was when they decided
to submit feedback.
> Provide url for a post-feedback submission success page

- mtp_prisoner_location_admin/settings/base.py
• all logs are prepended with their level
• all logs of level INFO or higher will be output to the console and ELK
• all logs of level ERROR or higher will also be sent to Sentry if configured
> Make django logging consistent between apps

- mtp_prisoner_location_admin/apps/feedback/urls.py
The path changed as a result of changes to mtp-common
> Correctly specify path of feedback_success template

- mtp_noms_ops/assets-src/javascripts/main.js
- mtp_noms_ops/assets-src/stylesheets/app-ie6.scss
- mtp_noms_ops/assets-src/stylesheets/app-ie7.scss
- mtp_noms_ops/assets-src/stylesheets/app-ie8.scss
- mtp_noms_ops/assets-src/stylesheets/views/_security-forms.scss
- mtp_noms_ops/settings/base.py
- mtp_noms_ops/templates/base.html
- mtp_noms_ops/templates/feedback/submit_feedback.html
- mtp_noms_ops/templates/prisoner_location_admin/location_file_upload.html
- mtp_noms_ops/templates/security/credits.html
- mtp_noms_ops/templates/security/dashboard.html
- mtp_noms_ops/templates/security/grouped-credits.html
- mtp_noms_ops/templates/security/grouped.html
- mtp_noms_ops/templates/security/search.html
- requirements/dev.txt
- requirements/docker.txt
- run.sh
- webpack.config.js
* use latest common
* require js scripts the standard way
* add stylesheets for old ie versions
* align to govuk visual styles,
* use govuk classes, markup and template
* find new govuk-templates
* make endblocks consistent
* adapt run script and webpack config
> remove Mojular:

- mtp_noms_ops/apps/prisoner_location_admin/tests/test_views.py
- mtp_noms_ops/urls.py
- requirements/dev.txt
- requirements/docker.txt
This is no longer needed as application restrictions are checked
in the API.
> Remove 'restrict_applications' argument to login view

- mtp_noms_ops/assets-src/javascripts/modules/security-forms.js
- mtp_noms_ops/assets-src/stylesheets/views/_security-forms.scss
- mtp_noms_ops/templates/security/grouped-credits.html
- mtp_noms_ops/templates/security/prisoner-grouped.html
- mtp_noms_ops/templates/security/sender-grouped.html
We don't expect no-js users (like cashbook). Therefore
we can simplify the table loaded as well as the corresponding
JS code. Styling is also simplified
> Remove non-ajax version of security searches

- mtp_noms_ops/apps/prisoner_location_admin/tests/test_functional.py
- mtp_noms_ops/apps/security/tests/test_functional.py
New password rules do not allow for a password of 'admin'.
> Update superuser password used on test environments

- mtp_noms_ops/apps/security/forms.py
The API deals with amounts in pence, so the value input by the
user needs to be multiplied by 100 when filtering on the total
value of credits in the grouped search screens.
> Convert input pounds to pence for amount min/max filtering

- mtp_noms_ops/apps/security/forms.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/apps/security/urls.py
- mtp_noms_ops/apps/security/views.py
- mtp_noms_ops/assets-src/javascripts/main.js
- mtp_noms_ops/assets-src/stylesheets/app.scss
- mtp_noms_ops/assets-src/stylesheets/views/_review.scss
- mtp_noms_ops/templates/base.html
- mtp_noms_ops/templates/security/credits.html
- mtp_noms_ops/templates/security/review.html
- mtp_noms_ops/utils.py
One of the stories that came out of research in the high security
estate was that security staff pre-approve credits before biz hub staff
pay the money to the prisoners. To support this, we have added a
payment review tool to allow security staff to sign off and leave
comments on incoming credits. The review status and comments are then
visible to the biz hub staff.
> Add tool for certain staff in some prisons to pre-approve credits

- mtp_noms_ops/apps/prisoner_location_admin/forms.py
- mtp_noms_ops/apps/prisoner_location_admin/tests/test_forms.py
As we cannot allocate payments to prisoners currently being
transferred, discard all such location records when parsing
file.
> Discard transfer records in prisoner location file

- mtp_noms_ops/apps/security/forms.py
- mtp_noms_ops/apps/security/templatetags/security.py
- mtp_noms_ops/apps/security/tests/test_functional.py
- mtp_noms_ops/apps/security/tests/test_utils.py
- mtp_noms_ops/assets-src/javascripts/modules/tabs.js
- mtp_noms_ops/templates/security/credits.html
- mtp_noms_ops/templates/security/forms/search-description.html
- mtp_noms_ops/templates/security/prisoners-detail.html
- mtp_noms_ops/templates/security/prisoners.html
- mtp_noms_ops/templates/security/review.html
- mtp_noms_ops/templates/security/senders-detail.html
- mtp_noms_ops/templates/security/senders.html
- mtp_noms_ops/translations/cy/LC_MESSAGES/django.po
- mtp_noms_ops/translations/en_GB/LC_MESSAGES/django.po
also…
• normalise some display text (e.g. "by debit card" rather than sometimes "Debit card")
• make amount filters re-populate the form correctly (rather than turning into pence values)
• clear optional fields that depend on drop-downs unless they're explicitly selected
• simplify translations that are not sentences anyway by removing HTML
> Improve descriptions of enabled filters in security views

- mtp_noms_ops/apps/security/forms.py
The review functionality is not relevant for already credited
credits, and when activating it for new prisons security users
should not be confronted with an incredibly long list.
> Only show yet to be credited credits for security review

- mtp_noms_ops/assets-src/stylesheets/views/_save-search.scss
Does not require as much margin when the language switcher is not present.
> Ensure pin profile is alwys level with top of heading

- mtp_noms_ops/apps/security/searches.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/urls.py
If the client receives a 'not found' response when checking the
endpoint for a saved search, delete the associated search.
> Automatically delete a saved search if the resource does not exist

- mtp_noms_ops/assets-src/stylesheets/views/_security-results.scss
So that printed pages for credits, prisoners and senders filtered lists look the same
> Make print layouts consistent for security filter results

- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/assets-src/stylesheets/views/_senders-detail.scss
- mtp_noms_ops/templates/security/senders-detail.html
As the last 4 digits and expiry date have been found to not be sufficient
to uniquely identify a card, need to inform people of this whilst we
work out how to deal with things.
> Add warning that not all credits may actually be from the same card

- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/urls.py
- mtp_noms_ops/apps/security/views.py
- mtp_noms_ops/assets-src/stylesheets/views/_prisoners-detail.scss
- mtp_noms_ops/templates/security/prisoners-detail.html
As retrieving the prisoner photo takes some time, do it asynchronously
with loading the page so that the user is not delayed from viewing the
information.
> Delay retrieving the prisoner photo until after page load

- mtp_noms_ops/apps/security/views.py
Instruct private caches to keep the image for up to a month.
> Cache prisoner images to avoid retrieving from NOMIS every time

- mtp_noms_ops/apps/security/templatetags/security.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/templates/security/credits.html
- mtp_noms_ops/templates/security/prisoners-detail.html
- mtp_noms_ops/templates/security/review.html
- mtp_noms_ops/templates/security/senders.html
Credits with unknown senders are aggregated into one 'unknown sender'
profile which is misleading. This sender profile should not show
in the list of senders, nor should it be linked to from other pages.
> Hide sender profile for unknown senders

- mtp_noms_ops/apps/security/forms.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/apps/security/views.py
by deferring api session creation until needed,
loading initial field values as defaults,
no longer requiring page field,
and deferring api object/object list requests until needed
(back-ported from cashbook)
> Update security forms and views to function a bit better

- mtp_noms_ops/assets-src/javascripts/main.js
- mtp_noms_ops/templates/dashboard.html
- mtp_noms_ops/templates/mtp_auth/login.html
Notifications can be set on the API and will display to users.
> Add notifications for communication with noms ops users

- mtp_noms_ops/apps/security/templatetags/security.py
- mtp_noms_ops/assets-src/stylesheets/views/_security-results.scss
- mtp_noms_ops/templates/mtp_auth/login.html
- requirements/dev.txt
- requirements/docker.txt
• disconnects user management overlap between noms-ops and cashbook
• does NOT yet allow sign-up, choosing/switching prison/region, managing requests (more mtp-api changes required first)
> Update compatibility with latest version of mtp-common

- mtp_noms_ops/apps/security/export.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/views.py
- mtp_noms_ops/templates/security/prisoner.html
This is to much changes to the API in order to disambiguate
from disbursement recipients.
> Change 'recipient_names' payment attribute to 'provided_names'

- mtp_noms_ops/assets-src/javascripts/main.js
- mtp_noms_ops/assets-src/javascripts/modules/form-analytics.js
- mtp_noms_ops/templates/security/credits.html
- mtp_noms_ops/templates/security/disbursements.html
- mtp_noms_ops/templates/security/includes/export-dialogue.html
- mtp_noms_ops/templates/security/prisoners.html
- mtp_noms_ops/templates/security/senders.html
This is to allow us to track what filters are used by users, as well
as when they try and export or print data.
> Create Google analytics events for the search parameters used

- mtp_noms_ops/apps/security/views/object_base.py
- mtp_noms_ops/templates/security/credits.html
- mtp_noms_ops/templates/security/disbursements.html
- mtp_noms_ops/templates/security/includes/export-dialogue.html
- mtp_noms_ops/templates/security/prisoners.html
- mtp_noms_ops/templates/security/senders.html
This changes the event action to be that of the general page title
rather than the specific record being looked at.
> Fix export event tag on detail pages

- mtp_noms_ops/apps/security/utils.py
- mtp_noms_ops/settings/base.py
- mtp_noms_ops/templates/base.html
- mtp_noms_ops/templates/dashboard.html
If a user with a default prison that is not a disbursement prison
goes to the disbursements page, the page will default to not filtering
by any prison.
> Avoid filtering by invalid default prison on disbursements page

- mtp_noms_ops/assets-src/javascripts/modules/choose-prisons.js
- mtp_noms_ops/assets-src/javascripts/modules/form-analytics.js
- mtp_noms_ops/settings/base.py
- mtp_noms_ops/templates/security/credits.html
- mtp_noms_ops/templates/security/disbursements.html
- mtp_noms_ops/templates/security/prisoner.html
- mtp_noms_ops/templates/security/prisoners.html
- mtp_noms_ops/templates/security/sender.html
- mtp_noms_ops/templates/security/senders.html
- requirements/dev.txt
- requirements/docker.txt
Send event attributes as positional arguments rather than a dict allows
a final dict argument to override page, location and title.
> Change GA event sending to be compatible with blanket param stripping

- mtp_noms_ops/apps/security/forms/object_base.py
- mtp_noms_ops/apps/security/forms/object_list.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/urls.py
On the API, the totals are now divided by time period, so the client
needs to allow for the selection of time period, have a default
time period to fall back to, and populate the totals of the
returned object according to the selected time period.
> Ensure compatibility with restructuring of totals on profiles

- mtp_noms_ops/apps/security/forms/object_detail.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/views/object_detail.py
- mtp_noms_ops/templates/security/includes/notification-table.html
- mtp_noms_ops/templates/security/prisoner.html
This was due to a change in method ordering meaning that one thing
was not initialised at the correct time. However, the way in which
disbursements were retrieved on the prisoner profile page was due
to be updated to the nested resource anyway, so I have done so.
> Fix disbursements list not showing up on prisoner profile

- mtp_noms_ops/apps/security/templatetags/security.py
credit does not promote all sender identifiable keys to top level: postcode is not available on credit object
> Fix review page

- mtp_noms_ops/apps/security/context_processors.py
- mtp_noms_ops/apps/security/templatetags/security.py
- mtp_noms_ops/apps/security/tests/test_templatetags.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/settings/tests/test_views.py
- mtp_noms_ops/apps/settings/views.py
- mtp_noms_ops/assets-src/stylesheets/app.scss
- mtp_noms_ops/assets-src/stylesheets/views/_prison_switcher.scss
- mtp_noms_ops/settings/base.py
- mtp_noms_ops/templates/security/credits.html
- mtp_noms_ops/templates/security/disbursements.html
- mtp_noms_ops/templates/security/forms/prison-switcher.html
- mtp_noms_ops/templates/security/prisoners.html
- mtp_noms_ops/templates/security/review.html
- mtp_noms_ops/templates/security/senders.html
- mtp_noms_ops/templates/security/senders_list.html
- mtp_noms_ops/utils.py
This adds a new Prison Switcher area to the top of some pages showing the first 4 prisons the user has set in his/her settings with a link to the exiting page responsible for changing this if needed.
If more than 4 prisons exist in the user settings, a 'x more' text is shown as well.
The user is redirected back to the page he/she was coming from after saving the form via the prison switcher.
I added the section to the new `security/base.html` template as it only applies to security pages but that makes it a bit weird as the dashboard now extends `security/base.html`. This dashboard template should really be in the `security` folder but it was already in the root folder so I'm okay to keep it this way.
@ushkarev let me know if you have anything else in mind instead.
> Prison switcher

- mtp_noms_ops/apps/security/forms/object_list.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/urls.py
- mtp_noms_ops/apps/security/views/__init__.py
- mtp_noms_ops/apps/security/views/object_base.py
- mtp_noms_ops/apps/security/views/object_list.py
- mtp_noms_ops/assets-src/stylesheets/app.scss
- mtp_noms_ops/assets-src/stylesheets/views/_security-form-fields.scss
- mtp_noms_ops/templates/base.html
- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/forms/top-area-object-list.html
- mtp_noms_ops/templates/security/senders_list.html
_Note: the API changes have not being made so the actual search doesn't behave exactly as expected_
This:
- implements simple search for credits
- refactors the tests in test_views to use mixins
- refactors some tests to use the responses context manager instead of `responses.activate`
- changes the css to better match the designs
The previous version didn't quite match the designs so I've made a few more visual changes.
As the new designs change the spacing around the header, I've decided to attach a new class to the body `mtp-with-spaced-header` so that we can select which pages have the new heading for now and when we are happy we could apply the class to all pages to make all of them consistent.
**Before**
**After**
I've also refactored the test_views quite a lot to use Mixins for the …
> Credits simple search box

- mtp_noms_ops/templates/security/senders_list.html
This adds a new template called `senders_list.html` with a new version of the payment source results list.
~The template is not currently used by any views at the moment but will be.
To check locally, change `security.views.object_list.SenderListView.template_name` to `'security/senders_list.html'`~
I've rebased so the new search now uses this updated template.
**A couple of things to note**
~ I've decided to vertically align the table cells in the middle as it looks tidier especially with those sorting background images. I could change this though.~
- I've made the `Payment method` column not sortable for now as changing it is not straightforward but I could try harder if it needs be
**Before**
**After**
> Redesign results list for payment sources

- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/disbursements_list.html
- mtp_noms_ops/templates/security/prisoners.html
- mtp_noms_ops/templates/security/senders_list.html
**Before:**
When an email was not available the template was simply omitting any value.
**After:**
The text `Email not provided` is used instead.
> Update copy when email not available in results list

- mtp_noms_ops/apps/security/views/object_base.py
- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/disbursements_list.html
- mtp_noms_ops/templates/security/forms/top-area-object-list.html
- mtp_noms_ops/templates/security/prisoners_list.html
- mtp_noms_ops/templates/security/senders_list.html
Hide the results list and change the copy to say that there were no results.
**Before**
**After**
> Redesign no search results case for simple search V2

- mtp_noms_ops/apps/security/templatetags/security.py
- mtp_noms_ops/apps/security/tests/test_templatetags.py
- mtp_noms_ops/assets-src/stylesheets/views/_security-results.scss
- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/disbursements_list.html
- mtp_noms_ops/templates/security/prisoners_list.html
- mtp_noms_ops/templates/security/senders_list.html
This adds 2 template tags to highlight search terms.
- `search_highlight` which wraps the text with a span
- `setup_hightlight` which caches the regex pattern so that it doesn't have to be computed every time
> Highlight search term when using simple search

- mtp_noms_ops/apps/security/templatetags/security.py
- mtp_noms_ops/apps/security/tests/test_templatetags.py
- mtp_noms_ops/templates/security/forms/prison-switcher.html
- mtp_noms_ops/templates/security/senders_list.html
A sender can have more than one email address and more than one cardholder name.
This adds a new template tag which makes it possible to implement a succinct `<best matching item> and more`.
As we want to highlight the search term on the results page, the template tag extract the best match in the list.
> Show best matching email/cardholder name in sender search results

- mtp_noms_ops/apps/security/templatetags/security.py
- mtp_noms_ops/apps/security/tests/test_templatetags.py
This:
- escapes the regex pattern so that a search term containing regex meaningful rules is treated as a raw string
- escapes the input value before wrapping search terms with highlight spans so that it's not mistakenly treated as html safe
> Make search highlighting more robust

- mtp_noms_ops/apps/security/forms/object_base.py
- mtp_noms_ops/apps/security/forms/object_list.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/urls.py
- mtp_noms_ops/apps/security/views/object_list.py
- mtp_noms_ops/assets-src/javascripts/modules/security-forms.js
- mtp_noms_ops/assets-src/stylesheets/views/_security-form-fields.scss
- mtp_noms_ops/templates/base.html
- mtp_noms_ops/templates/security/credits_advanced_search.html
- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/forms/split-date-field.html
This implements advanced search for credits.
Notes:
1. I created an `AmountSearchFormMixin` to keep the logic related to amount in one place instead of being a bit in the form, a bit in the enum.
2. I changed the show/hide javascript for amount pattern to support radio inputs as well.
> Credits advanced search

- mtp_noms_ops/apps/security/context_processors.py
- mtp_noms_ops/apps/security/forms/object_list.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/settings/tests/test_views.py
- mtp_noms_ops/assets-src/javascripts/modules/security-forms.js
- mtp_noms_ops/assets-src/stylesheets/views/_security-form-fields.scss
- mtp_noms_ops/templates/security/base_advanced_search.html
- mtp_noms_ops/templates/security/credits_advanced_search.html
- mtp_noms_ops/templates/security/disbursements_advanced_search.html
- mtp_noms_ops/templates/security/forms/prison-selector-fieldset.html
- mtp_noms_ops/templates/security/forms/prison-switcher.html
- mtp_noms_ops/templates/security/forms/top-area-object-list.html
- mtp_noms_ops/templates/security/forms/user-prison-names-ellipsis.html
- mtp_noms_ops/templates/security/prisoners_advanced_search.html
- mtp_noms_ops/templates/security/senders_advanced_search.html
This:
- adds a `prison_selector` field along with the existing `prison` field. Valid options for prison selector are: `All prisons`, `"My prisons"`, or `A specific prison`. When the last option is specified the prison field is required.
- some constants and functions in tests were renamed to keep things consistent
- the existing hide/reveal javascript was renamed to Legacy so that it'll be easier to find and remove when v2 goes live
I would suggest reviewing the commits individually.
Not in this PR and still to be implemented:
- removal of prison switcher in advanced search form and search results page
- extra `prison` column in search results table when using advanced search
> Prison selector in search forms V2

- mtp_noms_ops/apps/security/forms/object_list.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/templates/security/base_advanced_search.html
- mtp_noms_ops/templates/security/base_search_results.html
- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/disbursements_list.html
- mtp_noms_ops/templates/security/prisoners_list.html
- mtp_noms_ops/templates/security/senders_list.html
Depends on https://github.com/ministryofjustice/money-to-prisoners-api/pull/530
This:
- adds the `prison` column to the search results V2 page when using the advanced search
- removes the prison switcher when using the advanced search
- changes the prisoners search logic to use `current_prison` instead of the previous historic `prison`s.
> Advanced search refinement

- mtp_noms_ops/apps/security/forms/object_list.py
- mtp_noms_ops/apps/security/views/object_base.py
- mtp_noms_ops/templates/security/forms/top-area-object-list.html
This:
- removes the full stop in search results / search description copy
- changes breadcrumbs and page heading on the search results page to say _Advanced search results_ when using the advanced search
> Search copy changes

- mtp_noms_ops/apps/security/views/object_base.py
- mtp_noms_ops/assets-src/stylesheets/views/_security-results.scss
- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/disbursements_list.html
- mtp_noms_ops/templates/security/prisoners_list.html
- mtp_noms_ops/templates/security/senders_list.html
This:
Before: going back to the simple search form using the breadcrumbs would keep the search term and would filter the list.
After: the search term is reset so that it's obvious that the list below the form is not filtered
When clicked, it takes you to the simple search form or the advanced search form.
> Search again

- mtp_noms_ops/assets-src/stylesheets/views/_security-results.scss
Highlighting in the search results table was not displaying properly as there was insufficient vertical space between the lines in the table.
This gets rid of the border-bottom.
**Before**
**After**
> Remove border-bottom from search highlight

- mtp_noms_ops/assets-src/javascripts/modules/form-analytics.js
- requirements/dev.txt
- requirements/docker.txt
This sends ga pageview events when a user clicks on print or export so that the related data can be analysed along with other pageviews.
It depends on https://github.com/ministryofjustice/money-to-prisoners-common/pull/357
> Count export/print as pageviews

- mtp_noms_ops/apps/security/forms/object_list.py
- mtp_noms_ops/assets-src/javascripts/modules/form-analytics.js
- mtp_noms_ops/assets-src/stylesheets/views/_security-form-fields.scss
- mtp_noms_ops/assets-src/stylesheets/views/_security-results.scss
- mtp_noms_ops/templates/security/base_advanced_search.html
- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/disbursements_list.html
- mtp_noms_ops/templates/security/prisoners_list.html
- mtp_noms_ops/templates/security/senders_list.html
This:
**1/ Refactors the GA form events** 
We were sending one event per filter used with category name `SecurityForms`. 
We are now sending one event per filter used with category name `form-submitted-single-filter` PLUS one extra event with all combined filters used as a comma separated string with category name `form-submitted-combined-filters`.
Events are still sent using the legacy category name `SecurityForms` as well until we switch the search V2 on and we can safely delete it.
**2/ Renames export GA event to `form-link`**
We were using the event category `SecurityFormsExport` which wasn't great as it's supposed to be generic.
Events are still sent using the legacy category name `SecurityFormsExport` as well until we switch the search V2 on and we can safely delete it.
**3/ …
> GA refactoring

- mtp_noms_ops/templates/security/senders_list.html
Before we were showing the whole list which could be very long.
This implements the same logic used in other place where we only display the first 2 items with a 'x more' suffix.
**Before**
**After**
> Only show first 2 prisons in advanced search results for senders

- mtp_noms_ops/apps/feedback/urls.py
- mtp_noms_ops/assets-src/stylesheets/app.scss
- mtp_noms_ops/assets-src/stylesheets/views/_feedback-banner.scss
- mtp_noms_ops/templates/base.html
- mtp_noms_ops/templates/feedback/success.html
- mtp_noms_ops/templates/security/base_search_results.html
- mtp_noms_ops/templates/security/includes/feedback-banner.html
- mtp_noms_ops/utils.py
This adds a feedback banner to entry pages related to search V2 asking the user to leave feedback.
It also changes the text in main nav and feedback pages to include the word _feedback_.
> Feedback banner

- mtp_noms_ops/apps/security/context_processors.py
- mtp_noms_ops/settings/base.py
- mtp_noms_ops/utils.py
- requirements/dev.txt
- requirements/docker.txt
This adds the cloud platform migration middleware and sets up the related settings values as env vars.
There's one javascript error when the site is in maintenance or migration mode as `django` is not defined because of the missing `js-i18n.js`.
I'm not too worried about it as we don't really need any javascript (except ga) but I'm not sure if they would trigger sentry errors?
Fixing that is a bit painful but not too difficult and it probably requires changing https://github.com/ministryofjustice/money-to-prisoners-common/blob/master/mtp_common/assets-src/javascripts/modules/date-picker.js#L199 to support non-django-defined cases as well.
@ushkarev what do you think?
Update: fixed the data-picker.js to only init language strings when needed.
> Add support for cloud platform migration

- mtp_noms_ops/templates/security/base_search_results.html
- mtp_noms_ops/templates/security/includes/feedback-banner.html
The underlying logic is still in place in case we want to use the same banner for future features.
> Remove feedback banner inclusion from search results page

- mtp_noms_ops/apps/security/templatetags/security.py
so that "my prison" filter doesn't hide results and all searchable fields are available
> Use advanced search when redirecting to prisoner or sender profile

- .circleci/config.yml
- .github/CODEOWNERS
- Dockerfile
- README.md
- mtp_noms_ops/settings/base.py
- mtp_noms_ops/urls.py
- requirements/dev.txt
- requirements/docker.txt
- As apps are now able to discover each other, many environment variables are now redundant so they can be removed
- Apps now use base Docker images built by this repository (pulling from ECR or building locally) – this speeds up builds and ensures they have the same base OS
- Add prometheus service monitors for all apps
- Depends on [mtp-deploy#282](https://github.com/ministryofjustice/money-to-prisoners-deploy/pull/282)
> Remove template-deploy artefacts

- mtp_noms_ops/apps/security/forms/check.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/settings/base.py
This adds the ability to only include checks related to credits in initial state so that if payments time out, the linked checks don't show up.
It's behind a feature flag as we are currently running checks in simulation mode so if we enable this, none of the checks will appear.
> Only return pending checks related to credits in initial state

- mtp_noms_ops/templates/security/forms/top-area-object-list.html
The previous version was hiding error messages related to API issues.
> Show form errors in search result page

- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/disbursements_list.html
- mtp_noms_ops/templates/security/prisoners_list.html
- mtp_noms_ops/templates/security/senders_list.html
… because money that has *not* been credited will be listed as well
> Show credit and disbursement status in tables

- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/assets-src/stylesheets/views/_security-results.scss
- mtp_noms_ops/templates/security/accept_check.html
- mtp_noms_ops/templates/security/checks_list.html
- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/disbursements_list.html
- mtp_noms_ops/templates/security/includes/credit-header-row.html
- mtp_noms_ops/templates/security/includes/credit-row.html
- mtp_noms_ops/templates/security/includes/disbursement-header-row.html
- mtp_noms_ops/templates/security/includes/disbursement-row.html
- mtp_noms_ops/templates/security/prisoner-disbursements.html
- mtp_noms_ops/templates/security/prisoner.html
- mtp_noms_ops/templates/security/prisoners_list.html
- mtp_noms_ops/templates/security/reject_check.html
- mtp_noms_ops/templates/security/review.html
- mtp_noms_ops/templates/security/sender.html
- mtp_noms_ops/templates/security/senders_list.html
This makes credit and disbursement lists on sub-pages (prisoner and sender profiles) look more like the 4 top-level lists
> Consistent tables

- mtp_noms_ops/apps/security/__init__.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/urls.py
- mtp_noms_ops/apps/security/utils.py
- mtp_noms_ops/apps/settings/forms.py
- mtp_noms_ops/apps/settings/tests/test_forms.py
- mtp_noms_ops/apps/settings/tests/test_views.py
- mtp_noms_ops/apps/settings/urls.py
- mtp_noms_ops/apps/settings/views.py
- mtp_noms_ops/assets-src/javascripts/modules/security-forms.js
- mtp_noms_ops/assets-src/stylesheets/app.scss
- mtp_noms_ops/assets-src/stylesheets/views/_job-information-form.scss
- mtp_noms_ops/templates/settings/job-information.html
- ~I'm not happy with the early return in the Job Information `form_valid` method (see inline comment for details).~
- The templates in mtp-common didn't quite fit the requirements of the prototype/design - but we decided it wasn't worth updating them to be able to just include the templates for radios and textarea, a better plan is probably update them and make them more flexible when reworking them in the GDS styles update work.
Jira: https://dsdmoj.atlassian.net/browse/MTP-1266
This commit adds a form to the Intelligence tool which will collect
information about an user's job title, the area of the prison estate
they work in and what their job title involves.
By using the flags used elsewhere in this app we only redirect a user
to a form if they have not previously completed the …
> Add Job Information Form

- mtp_noms_ops/apps/security/tests/test_views.py
Flake8 complained about `./mtp_noms_ops/apps/security/tests/test_views.py:1143:14: F541 f-string is missing placeholders`
so just removing the formatting, as plain strings in tests don't need
it.
https://app.circleci.com/pipelines/github/ministryofjustice/money-to-prisoners-noms-ops/629/workflows/a5df5697-706b-486b-a0c3-05178c57ed1c/jobs/648
Still unsure why the failures appeared suddenly, flake8 config or something must have changed as I see no other reason for this cropping up where previously it was fine (for a long time)
> Fix new code style error raised by flake8

- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/templates/security/credits_history_list.html
If the decision reason is blank, as can be the case for accepted checks
we shouldn't show an empty label in the UI.
> Conditionally display decision details label

- mtp_noms_ops/apps/security/forms/check.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/settings/base.py
Before delayed capture functionality was enabled, there was a period during which checks were being created and automatically accepted as a preview for FIU. These should not appear in the history page since nobody "actioned" them.
[#MTP-1447](https://dsdmoj.atlassian.net/browse/MTP-1447)
> Filter out irrelevant demo security checks

- mtp_noms_ops/assets-src/javascripts/main.js
- mtp_noms_ops/assets-src/javascripts/modules/disable-on-submit.js
- mtp_noms_ops/templates/prisoner_location_admin/location_file_upload.html
…to prevent concurrent submission when users double-click. Concurrent submissions of this form result in incomplete lists of locations being stored.
> Disable submit button when prisoner location report is uploaded

- mtp_noms_ops/apps/security/forms/check.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/urls.py
- mtp_noms_ops/apps/security/views/__init__.py
- mtp_noms_ops/apps/security/views/check.py
- mtp_noms_ops/assets-src/stylesheets/views/_checks.scss
- mtp_noms_ops/templates/security/accept_or_reject_check.html
1. Is this approach a decent thing? Wasn't sure about just having redirects as the handling of the view
2. Will this handle invalid forms? I can't think of a case where the form would be invalid, but guess there could be things I missed
3. Are the tests comprehensive enough - I feel like I have nothing connecting actually hitting the button on the AcceptRejectView
Jira: https://dsdmoj.atlassian.net/browse/MTP-1452
This commit adds the ability to assign a check to a user so that they
can manage the checks they are or want to work on.
As there is no interface and it's initially just going to be done on the
Resolve credit page, we handle the form using a view that will just
redirect back to the resolve_check view.
The handling of GET requests is to get round an issue where django will …
> MTP-1452 Add assign functionality for security checks

- mtp_noms_ops/settings/base.py
- requirements/dev.txt
- requirements/docker.txt
The new endpoint that HMPPS has chosen does not include `/elite2api/` in the URL. Because this is a breaking change and client apps must have updated settings, it seems safest to require new settings names entirely. The settings names are now more descriptive of what HMPPS is calling the associated components.
Depends on [common-383](https://github.com/ministryofjustice/money-to-prisoners-common/pull/383) and [deploy-305](https://github.com/ministryofjustice/money-to-prisoners-deploy/pull/305).
[MTP-1484](https://dsdmoj.atlassian.net/browse/MTP-1484)
> Update Prison API (i.e. NOMIS) connector url handling

- .circleci/config.yml
- .dockerignore
- requirements/dev.txt
a) this shouldn't be really necessary as it's already in the .gitignore b) docker-compose does support custom .dockerignore to dockerfile mapping, but it doesn't seem to actually work right now (see comments under ticked answer on https://stackoverflow.com/questions/40904409/how-to-specify-different-dockerignore-files-for-different-builds-in-the-same-pr
> MTP-1469 Moved local.py dockerignore out of root defintion and added it within CI task instead

- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/urls.py
- mtp_noms_ops/apps/security/views/object_list.py
- mtp_noms_ops/apps/security/views/views.py
- mtp_noms_ops/settings/base.py
- mtp_noms_ops/templates/dashboard.html
- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/disbursements_list.html
- mtp_noms_ops/templates/security/policy-change-info.html
- mtp_noms_ops/templates/security/policy-change-warning.html
This is similar to the cashbook changes. I used the NOVEMBER_SECOND_CHANGES_LIVE changes rather thane BANK_TRANSFERS_ENABLED which is different to the cashbook, but I think this is better - but would it be better to have consistency for when it comes to removing these changes? I think it's OK, as it'll mostly just all be ripped out fairly soon, so shouldn't be too confusing.
> MTP 1598 Post 2 nov banner updates

- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/urls.py
- mtp_noms_ops/apps/security/views/check.py
- mtp_noms_ops/templates/security/checks_list.html
Jira: https://dsdmoj.atlassian.net/browse/MTP-1700
When an FIU user added a check to their list from a page other than the
first page, the user request would be actioned and the user redirected
back to the list view. However the page param was not maintained, and
the user would be sent back to page one, regardless of which page they
were currently on.
This commit addresses that by passing the current page through with the
check data to allow the redirect to maintain the current page for the
user.
> MTP-1700 Maintain current page in FIU Check List

- mtp_noms_ops/apps/security/constants.py
- mtp_noms_ops/apps/security/forms/check.py
- mtp_noms_ops/apps/security/tests/test_forms.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/utils.py
- mtp_noms_ops/apps/security/views/check.py
- mtp_noms_ops/assets-src/stylesheets/views/_checks.scss
- mtp_noms_ops/templates/security/accept_or_reject_check.html
- requirements/dev.txt
Ticket link: https://dsdmoj.atlassian.net/browse/MTP-1738
Relies on: https://github.com/ministryofjustice/money-to-prisoners-api/pull/626/
To discuss:
* https://dsdmoj.atlassian.net/browse/MTP-1738?focusedCommentId=132135
* What to do on auto-accept POST/PATCH failure. Do we revert the state of the check, otherwise they won't be able to make another attempt at creating an auto-accept rule
TODO:
> MTP-1738 Add an auto-accept rule 

- mtp_noms_ops/templates/security/notifications.html
…which were accidentally left off in the [GOV.UK design system updates](https://github.com/ministryofjustice/money-to-prisoners-noms-ops/pull/517).
This simply wraps existing content into lists, which is what the notifications are: lists of links. This will make the markup match the semantics of what we're showing, but have no visual impact.
> Update display of notifications

- mtp_noms_ops/apps/security/views/dashboard.py
- mtp_noms_ops/apps/security/views/object_list.py
- mtp_noms_ops/templates/dashboard.html
- mtp_noms_ops/templates/security/credits_list.html
- mtp_noms_ops/templates/security/disbursements_list.html
… as it's been 4 months so all users will have seen them. We don't want to distract people from other, more important, messages that we may wish to show instead.
The page they linked to remains in case it's been linked to and in case we may want to refer users in future.
[MTP-1808](https://dsdmoj.atlassian.net/browse/MTP-1808)
> Remove banners announcing November 2020 policy changes

- requirements/base.txt
Bump `mtp-common` to `11.1.0` and remove dependencies which are already
requested there. This reduce duplication and reduce the risk of clashes
between packages versions.
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1537
> MTP-1537: Remove dependencies in mtp-common (11.1.0)

- mtp_noms_ops/apps/security/views/dashboard.py
…for users whose monitored list is too long so the `new_result_count` values are not populated. this key was previously only used in the template so was ignored if it was missing.
> Fix dashboard display of saved searches

- mtp_noms_ops/apps/views.py
- mtp_noms_ops/templates/faq.html
- mtp_noms_ops/templates/govuk-frontend/components/footer.html
- mtp_noms_ops/templates/mtp_auth/login.html
- mtp_noms_ops/urls.py
When user is not signed in, the links to "Get help" no longer take them
to the "Submit feedback" page but instead they take them to an FAQ page
with questions related to login problems etc.
This FAQ page still has links to contact us.
⚠️ **NOTE**: Currently the 'Request an account' functionality is not present in `noms-ops` (see ['Request an account - intel tool' epic](https://dsdmoj.atlassian.net/browse/MTP-1812)). 
So in the interest of making this releasable the question with the link to 'request an account' take the user to the 'Submit a ticket' page with a pre-populated message.
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1837
> MTP-1837: FAQ (when signed out)

- mtp_noms_ops/templates/faq.html
- mtp_noms_ops/templates/security/faq.html
Updated the pre-populated messages in the 'Contact us' form for some
of the links in the FAQs as per copy document:
https://docs.google.com/document/d/1n6BM4nPkJmnL7fOFSpRk-pFyxUUUo1Z-Zho6GmC3kzo/edit
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1848
> MTP-1848: Update copy of pre-populated 'Contact us' from FAQs

- mtp_noms_ops/apps/mtp_auth/forms.py
- mtp_noms_ops/apps/mtp_auth/tests/test_views.py
- mtp_noms_ops/apps/mtp_auth/urls.py
- mtp_noms_ops/apps/mtp_auth/views.py
- mtp_noms_ops/apps/settings/tests/test_views.py
- mtp_noms_ops/apps/views.py
- mtp_noms_ops/settings/base.py
- mtp_noms_ops/templates/mtp_auth/login.html
- mtp_noms_ops/templates/mtp_common/user_admin/new-account-request-ticket.txt
- mtp_noms_ops/templates/mtp_common/user_admin/sign-up-success.html
- mtp_noms_ops/templates/mtp_common/user_admin/sign-up.html
- mtp_noms_ops/urls.py
Users can request an account directly. 
It uses [existing 'Account Request' functionality in `api`](https://github.com/ministryofjustice/money-to-prisoners-api/blob/8f7882917a5ccce1d0bd7a7a529e9bab523590de/mtp_api/apps/mtp_auth/urls.py#L11) with some tweaks.
⚠️ **NOTE**: As prison is optional for these account requests and as a new "Your manager's email" field needs to be added, this PR is [dependent on the corresponding `api` PR](https://github.com/ministryofjustice/money-to-prisoners-api/pull/649) to be merged.
Ticket: https://dsdmoj.atlassian.net/browse/MTP-1813
Prototype starts: https://pm-intelligence-tool.herokuapp.com/sign-in
> MTP-1813: Request an intel tool account

- mtp_noms_ops/apps/security/urls.py
…to match all other url formats
> Include trailing slash in auto-accept rule detail url

- mtp_noms_ops/templates/security/accept_or_reject_check.html
- mtp_noms_ops/templates/security/credits_history_list.html
If a credit was accepted or rejected only with "further details", 2 labels were displayed. Now, the "further details" label is displayed only if the credit was rejected and other reasons had been given as well.
> Prevent repetition of labels when displaying only "further details" on actioned credits

- mtp_noms_ops/apps/security/constants.py
- mtp_noms_ops/apps/security/forms/check.py
- mtp_noms_ops/apps/security/forms/object_list.py
- mtp_noms_ops/apps/security/templatetags/security.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/templates/security/accept_or_reject_check.html
- mtp_noms_ops/templates/security/credits_history_list.html
So that the definitions/labels are shared amongst all MTP apps and therefore data from DB can be consistently understood throughout.
See related `mtp-common` PR: https://github.com/ministryofjustice/money-to-prisoners-common/pull/421
> Move security check rejection reasons to mtp-common

- mtp_noms_ops/apps/security/tests/test_utils.py
- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/utils.py
Recent changes in logging levels revealed that some tests were using timezone-naive date-times.
• `mtp-api` always uses timezone-aware dates and the parsing mechanism assumes this
• tests no longer hard-code the time zone which should be determined by django settings
> Use timezone-aware dates in tests to match api responses

- mtp_noms_ops/settings/base.py
…at 30% sample rate in production (this is a medium traffic app) and 100% in other environments.
> Turn on Sentry.io performance monitoring

- mtp_noms_ops/apps/security/tests/test_views.py
- mtp_noms_ops/apps/security/views/check.py
- mtp_noms_ops/templates/security/accept_or_reject_check.html
… as it was taking too long to load when someone has sent several hundred credits in the past.
> Limit the number of “Credit decisions matching debit card or prisoner” displayed on credit review page

- mtp_noms_ops/settings/base.py
- mtp_noms_ops/tasks.py
- noms_ops.ini
- requirements/base.txt
- requirements/dev.txt
uWSGI now runs in lazy mode such that each process loads its own complete application rather than forking the master. This now requires the spooler to setup django.
Lazy apps are needed if telemetry is to be sent to Azure Application Insights: the `opencensus` library starts a background thread on launch to transport telemetry to Azure, but if uWSGI loads the application and _then_ forks, this thread is no longer accessible from the new process.
In `prod` environment:
• `mtp` logs of level INFO and higher
• other logs of level WARNING and higher
• 10% of requests traces
…will be sent.
Depends on [common#539](https://github.com/ministryofjustice/money-to-prisoners-common/pull/539).
> MTP-1921: Add Azure Application Insights request tracing and logging

- README.md
- mtp_noms_ops/apps/prisoner_location_admin/forms.py
- mtp_noms_ops/apps/security/forms/check.py
- mtp_noms_ops/apps/security/forms/eligibility.py
- mtp_noms_ops/apps/security/forms/object_base.py
- mtp_noms_ops/apps/security/forms/object_list.py
- mtp_noms_ops/apps/security/forms/review.py
- requirements/base.txt
- requirements/dev.txt
- removed `GARequestErrorReportingMixin` from forms
- removed now unnecessary `get_ga_event_category()` method from `SearchFormV2Mixin` - this was taking advantage of an hook in `django-form-error-reporting` to customise the `category` property of the event sent to GA - it shouldn't be unnecessary now
- bumped mtp-common to version `15.0.0` (unreleased atm)
> MTP-1937: Remove dependency on `django-form-error-reporting` mixins

- mtp_noms_ops/assets-src/components/choose-prisons/index.js
- mtp_noms_ops/assets-src/components/form-analytics/index.js
- mtp_noms_ops/settings/base.py
- removed setting
- removed call to now deprecated `Analytics.js`'s legacy GA `.send()`/`.rawSend()`
> MTP-1937: Stop trying to send data to legacy GA

- mtp_noms_ops/apps/prisoner_location_admin/management/commands/load_locations_from_offender_search.py
- mtp_noms_ops/apps/prisoner_location_admin/tests/test_management_commands.py
- mtp_noms_ops/apps/security/forms/check.py
- mtp_noms_ops/apps/security/tests/test_forms.py
…when _not in production_ environment because HMPPS Prisoner Search service is turned off and returns `503 Service Temporarily Unavailable`
> Prevent scheduled prisoner location uploading outside of office hours

- mtp_noms_ops/apps/security/forms/check.py
- mtp_noms_ops/apps/security/tests/test_views/test_checks.py
- mtp_noms_ops/apps/security/views/check.py
- mtp_noms_ops/templates/security/accept_or_reject_check.html
- mtp_noms_ops/templates/security/check_list.html
There are many pages of security checks to resolve. Users may be on a certain page and for whatever reason they want to be able to get back to the page they were at after accepting/rejecting a check.
The page where they were - usually the Checks list page, but it could also be in the "My list" page - is now remembered by the form. After resolving the Check the user is redirected to this page.
If for whatever reason this is missing they're taken back to the first page of the Checks list as before.
> MTP-1977: Redirect users back after accepting/rejecting a check.
